name: docker_data

services:
  portainer:
    image: 6053537/portainer-ce:latest
    container_name: portainer
    restart: always
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
    command: --schedule "0 0 */2 * * *" --cleanup --remove-volumes

  openlist:
    image: openlistteam/openlist:latest
    container_name: openlist
    restart: always
    network_mode: bridge
    user: "1001:1001"
    volumes:
      - /docker_data/openlist:/opt/openlist/data
    ports:
      - "5244:5244"
    environment:
      - TZ=Asia/Shanghai
      - UMASK=022

  lucky:
    image: gdy666/lucky:v3
    container_name: lucky
    restart: always
    network_mode: host
    volumes:
      - /docker_data/luckyconf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    network_mode: bridge
    volumes:
      - /docker_data/bitwarden:/data
    ports:
      - "8081:80"
    environment:
      - TZ=Asia/Shanghai
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=true

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    networks:
      - searxng-net
    ports:
      - "9001:8080"
    volumes:
      - /docker_data/searxng/core-config:/etc/searxng:rw
      - searxng-cache:/var/cache/searxng
    environment:
      - TZ=Asia/Shanghai
      - SEARXNG_BASE_URL=http://localhost:9001
      - SEARXNG_SECRET_KEY=0b58fbfb9f08a8348b6db355a8c59e12d2b8f36248007a5f014fdca1331970c4
    depends_on:
      - searxng-redis

  searxng-redis:
    image: redis:alpine
    container_name: searxng-redis
    restart: always
    networks:
      - searxng-net
    volumes:
      - searxng-redis-data:/data

networks:
  searxng-net:
    name: docker_data_searxng-net

volumes:
  searxng-cache:
  searxng-redis-data:
